// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
namespace AssemblyCSharp
{
	public class AccellGyroModel
	{

		public float ScaledAccellX;
		public float ScaledAccellY;
		public float ScaledAccellZ;
		public float ScaledGyroX;
		public float ScaledGyroY;
		public float ScaledGyroZ;
		public float RotX;
		public float RotY;

		public AccellGyroModel (float axs, float ays, float azs, float gxs, float gys, float gzs, float rox, float roy)
		{
			ScaledAccellX = axs;
			ScaledAccellY = ays;
			ScaledAccellZ = azs;
			ScaledGyroX = gxs;
			ScaledGyroY = gys;
			ScaledGyroZ = gzs;
			RotX = rox;
			RotY = roy;
		}
	}
}

